// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8FxZLT2UDMhMO1gbiHOsd1XGhC4sGGG8',
    appId: '1:863600410037:web:8c377a87f03a0a9a45adfc',
    messagingSenderId: '863600410037',
    projectId: 'flutter-firebase-cee42',
    authDomain: 'flutter-firebase-cee42.firebaseapp.com',
    storageBucket: 'flutter-firebase-cee42.appspot.com',
    measurementId: 'G-6V0S4ZC58Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsH_bYpxLLmggao2HCr9W6SO_WlM_jy5w',
    appId: '1:863600410037:android:65ffb82b07ffc18c45adfc',
    messagingSenderId: '863600410037',
    projectId: 'flutter-firebase-cee42',
    storageBucket: 'flutter-firebase-cee42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjnHsgUcg6k1Twld18hczo6Lby9lhunww',
    appId: '1:863600410037:ios:0f6fd10f9aba939e45adfc',
    messagingSenderId: '863600410037',
    projectId: 'flutter-firebase-cee42',
    storageBucket: 'flutter-firebase-cee42.appspot.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjnHsgUcg6k1Twld18hczo6Lby9lhunww',
    appId: '1:863600410037:ios:0f6fd10f9aba939e45adfc',
    messagingSenderId: '863600410037',
    projectId: 'flutter-firebase-cee42',
    storageBucket: 'flutter-firebase-cee42.appspot.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8FxZLT2UDMhMO1gbiHOsd1XGhC4sGGG8',
    appId: '1:863600410037:web:dddef48ecce8fdcf45adfc',
    messagingSenderId: '863600410037',
    projectId: 'flutter-firebase-cee42',
    authDomain: 'flutter-firebase-cee42.firebaseapp.com',
    storageBucket: 'flutter-firebase-cee42.appspot.com',
    measurementId: 'G-CK0FVYYVL8',
  );
}
